# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01_styles.base.ipynb.

# %% auto 0
__all__ = ['setup_open_props']

# %% ../../nbs/01_styles.base.ipynb 2
def setup_open_props():
    """Setup core OpenProps styles and theme variables"""
    return Style("""
        @import "https://unpkg.com/open-props";
        @import "https://unpkg.com/open-props/normalize.min.css";
        
        :where(html) {
            --color-scheme: light dark;
            --palette-hue: var(--oklch-teal);
            --palette-hue-rotate-by: 5;
            --palette-chroma: 0.89;
            /* ... other theme variables ... */
        }
    """)
