# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/03_components.actions.ipynb.ipynb.

# %% auto 0
__all__ = ['Button', 'ButtonGroup']

# %% ../../nbs/03_components.actions.ipynb.ipynb 1
def Button(*c, variant=None, size=None, disabled=False, icon_only=False, **kwargs):
    """Button component matching OpenPropsUI specs
    
    Args:
        *c: Child components
        variant: One of "outlined", "tonal", "filled", "elevated"
        size: One of "small", "large"
        disabled: Whether button is disabled
        icon_only: Whether button contains only an icon
        **kwargs: Additional HTML attributes
    """
    classes = ['button']
    if variant:
        classes.append(variant)
    if size:
        classes.append(size)
    if icon_only:
        classes.append('icon-only')
    
    return ft_hx('button',
        *c,
        class_=' '.join(classes),
        disabled=disabled,
        **kwargs
    )

# %% ../../nbs/03_components.actions.ipynb.ipynb 2
def ButtonGroup(*c, **kwargs):
    """Button group following OpenPropsUI specs
    
    Args:
        *c: Child components (Button components)
        **kwargs: Additional HTML attributes
    """
    return ft_hx('div',
        *c,
        class_='button-group',
        role='group',
        **kwargs
    )
