# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/fasthtml_opui',
                'doc_host': 'https://Deufel.github.io',
                'git_url': 'https://github.com/Deufel/fasthtml_opui',
                'lib_path': 'fasthtml_opui'},
  'syms': { 'fasthtml_opui.components.actions': { 'fasthtml_opui.components.actions.Button': ( 'components.actions.ipynb.html#button',
                                                                                               'fasthtml_opui/components/actions.py'),
                                                  'fasthtml_opui.components.actions.ButtonGroup': ( 'components.actions.ipynb.html#buttongroup',
                                                                                                    'fasthtml_opui/components/actions.py')},
            'fasthtml_opui.core': {'fasthtml_opui.core.foo': ('core.html#foo', 'fasthtml_opui/core.py')},
            'fasthtml_opui.styles.base': { 'fasthtml_opui.styles.base.setup_open_props': ( 'styles.base.html#setup_open_props',
                                                                                           'fasthtml_opui/styles/base.py')},
            'fasthtml_opui.styles.buttons': { 'fasthtml_opui.styles.buttons.setup_button_styles': ( 'styles.buttons.html#setup_button_styles',
                                                                                                    'fasthtml_opui/styles/buttons.py')}}}
