# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/fasthtml_opui',
                'doc_host': 'https://Deufel.github.io',
                'git_url': 'https://github.com/Deufel/fasthtml_opui',
                'lib_path': 'fasthtml_opui'},
  'syms': { 'fasthtml_opui.core': { 'fasthtml_opui.core.OpenProps': ('core.html#openprops', 'fasthtml_opui/core.py'),
                                    'fasthtml_opui.core.OpenPropsSync': ('core.html#openpropssync', 'fasthtml_opui/core.py'),
                                    'fasthtml_opui.core.OpenPropsSync.__init__': ( 'core.html#openpropssync.__init__',
                                                                                   'fasthtml_opui/core.py'),
                                    'fasthtml_opui.core.OpenPropsSync.sync_all': ( 'core.html#openpropssync.sync_all',
                                                                                   'fasthtml_opui/core.py'),
                                    'fasthtml_opui.core.OpenPropsSync.sync_openprops': ( 'core.html#openpropssync.sync_openprops',
                                                                                         'fasthtml_opui/core.py'),
                                    'fasthtml_opui.core.OpenPropsSync.sync_opui': ( 'core.html#openpropssync.sync_opui',
                                                                                    'fasthtml_opui/core.py')}}}
