# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['OpenPropsSync', 'OpenProps']

# %% ../nbs/00_core.ipynb 3
from pathlib import Path
import httpx
import shutil
from typing import Literal

from fasthtml.common import Link




# %% ../nbs/00_core.ipynb 4
class OpenPropsSync:
    """Sync OpenProps and OpenProps UI files to local static directory"""
    OPENPROPS_CDN = "https://unpkg.com/open-props@2.0.0-beta.5"
    OPUI_GITHUB = "https://raw.githubusercontent.com/felix-bohlin/ui/refs/heads/main/src"

    def __init__(self, static_dir=None):
        self.static_dir = Path(static_dir or 'static')
        self.css_dir = self.static_dir / 'css'
        self.op_dir = self.css_dir / 'opbeta'
        self.custom_dir = self.css_dir / 'custom'  # New directory for custom/edge case styles

    def sync_openprops(self):
        """Sync OpenProps files"""
        # Original directory structure
        self.op_dir.mkdir(parents=True, exist_ok=True)
        (self.op_dir / 'css').mkdir(exist_ok=True)
        (self.op_dir / 'css/color').mkdir(parents=True, exist_ok=True)
        (self.op_dir / 'css/sizes').mkdir(parents=True, exist_ok=True)
        (self.op_dir / 'css/font').mkdir(parents=True, exist_ok=True)
        (self.op_dir / 'css/packs').mkdir(parents=True, exist_ok=True)
        self.custom_dir.mkdir(parents=True, exist_ok=True)  # Create custom directory

        # Files to sync
        files = [
            'index.css',
            'css/media-queries.css',
            'css/sizes/media.css',
            'css/font/lineheight.css',
            'css/color/hues.oklch.css',
        ]

        # Sync regular files
        for file in files:
            response = httpx.get(f"{self.OPENPROPS_CDN}/{file}")
            if response.status_code == 200:
                (self.op_dir / file).write_text(response.text)
                print(f"Synced {file}")

        # Sync utilities to custom directory
        response = httpx.get(f"{self.OPENPROPS_CDN}/utilities.css")
        if response.status_code == 200:
            (self.custom_dir / 'utilities.css').write_text(response.text)
            print("Synced utilities.css to custom directory")

    def sync_custom_css(self, url, filename):
        """Sync a custom CSS file from any URL to the custom directory"""
        response = httpx.get(url)
        if response.status_code == 200:
            (self.custom_dir / filename).write_text(response.text)
            print(f"Synced custom CSS: {filename}")
        else:
            print(f"Failed to sync {filename}: {response.status_code}")

    def sync_opui(self):
        """Sync OpenProps UI files"""
        # Core files
        core_files = ['normalize.css', 'utils.css', 'theme.css', 'main.css']
        for file in core_files:
            response = httpx.get(f"{self.OPUI_GITHUB}/{file}")
            if response.status_code == 200:
                (self.css_dir / file).write_text(response.text)
                print(f"Synced {file}")

        # Component directories
        components = {
            'actions': ['button.css', 'button-group.css', 'icon-button.css', 'toggle-button-group.css'],
            'data-display': ['avatar.css', 'badge.css', 'card.css', 'chip.css', 'definition-list.css',
                           'divider.css', 'link.css', 'table.css', 'accordion.css', 'list.css'],
            'feedback': ['progress.css', 'spinner.css', 'alert.css', 'dialog.css', 'snackbar.css'],
            'inputs': ['checkbox-radio.css', 'switch.css', 'range.css', 'field-group.css', 'field.css',
                      'select.css', 'text-field.css', 'textarea.css'],
            'text': ['typography.css', 'rich-text.css']
        }

        for dir_name, files in components.items():
            dir_path = self.css_dir / dir_name
            dir_path.mkdir(parents=True, exist_ok=True)

            for file in files:
                response = httpx.get(f"{self.OPUI_GITHUB}/{dir_name}/{file}")
                if response.status_code == 200:
                    (dir_path / file).write_text(response.text)
                    print(f"Synced {dir_name}/{file}")

    def sync_all(self):
        """Sync all files"""
        print("Syncing OpenProps files...")
        self.sync_openprops()
        print("\nSyncing OpenProps UI files...")
        self.sync_opui()
        print("\nSync complete!")

# %% ../nbs/00_core.ipynb 5
def OpenProps(*additional_css):
    """FastHTML header components for OpenProps UI
    
    Args:
        *additional_css: Variable number of additional CSS files to include,
                        relative to the static/css directory
    """
    stylesheets = [
        Link(rel='stylesheet', href='static/css/main.css'),
    ]
    
    # Add any additional stylesheets
    for css in additional_css:
        stylesheets.append(Link(rel='stylesheet', href=f'static/css/{css}'))
    
    return stylesheets
