# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['ColorType', 'ModeType', 'OpenPropsSync', 'OpenProps']

# %% ../nbs/00_core.ipynb 3
from pathlib import Path
import httpx
import shutil
from typing import Literal


# %% ../nbs/00_core.ipynb 4
class OpenPropsSync:
    """Sync OpenProps and OpenProps UI files to local static directory"""
    OPENPROPS_CDN = "https://unpkg.com/open-props@2.0.0-beta.5"
    OPUI_GITHUB = "https://raw.githubusercontent.com/felix-bohlin/ui/refs/heads/main/src"

    def __init__(self, static_dir=None):
        self.static_dir = Path(static_dir or 'static')
        self.css_dir = self.static_dir / 'css'
        self.op_dir = self.css_dir / 'opbeta'

    def sync_openprops(self):
        """Sync OpenProps files"""
        # Create directory structure
        self.op_dir.mkdir(parents=True, exist_ok=True)
        (self.op_dir / 'css').mkdir(exist_ok=True)
        (self.op_dir / 'css/color').mkdir(parents=True, exist_ok=True)
        (self.op_dir / 'css/sizes').mkdir(parents=True, exist_ok=True)
        (self.op_dir / 'css/font').mkdir(parents=True, exist_ok=True)
        (self.op_dir / 'css/packs').mkdir(parents=True, exist_ok=True)

        # Files to sync
        files = [
            'index.css',
            'css/media-queries.css',
            'css/sizes/media.css',
            'css/font/lineheight.css',
            'css/color/hues.oklch.css',
            'utilities.css'
        ]

        for file in files:
            response = httpx.get(f"{self.OPENPROPS_CDN}/{file}")
            if response.status_code == 200:
                (self.op_dir / file).write_text(response.text)
                print(f"Synced {file}")

    def sync_opui(self):
        """Sync OpenProps UI files"""
        # Core files
        core_files = ['normalize.css', 'utils.css', 'theme.css', 'main.css']
        for file in core_files:
            response = httpx.get(f"{self.OPUI_GITHUB}/{file}")
            if response.status_code == 200:
                (self.css_dir / file).write_text(response.text)
                print(f"Synced {file}")

        # Component directories
        components = {
            'actions': ['button.css', 'button-group.css', 'icon-button.css', 'toggle-button-group.css'],
            'data-display': ['avatar.css', 'badge.css', 'card.css', 'chip.css', 'definition-list.css',
                           'divider.css', 'link.css', 'table.css', 'accordion.css', 'list.css'],
            'feedback': ['progress.css', 'spinner.css', 'alert.css', 'dialog.css', 'snackbar.css'],
            'inputs': ['checkbox-radio.css', 'switch.css', 'range.css', 'field-group.css', 'field.css',
                      'select.css', 'text-field.css', 'textarea.css'],
            'text': ['typography.css', 'rich-text.css']
        }

        for dir_name, files in components.items():
            dir_path = self.css_dir / dir_name
            dir_path.mkdir(parents=True, exist_ok=True)

            for file in files:
                response = httpx.get(f"{self.OPUI_GITHUB}/{dir_name}/{file}")
                if response.status_code == 200:
                    (dir_path / file).write_text(response.text)
                    print(f"Synced {dir_name}/{file}")

    def sync_all(self):
        """Sync all files"""
        print("Syncing OpenProps files...")
        self.sync_openprops()
        print("\nSyncing OpenProps UI files...")
        self.sync_opui()
        print("\nSync complete!")

# %% ../nbs/00_core.ipynb 5
ColorType = Literal['red', 'pink', 'purple', 'violet', 'indigo', 
                   'blue', 'cyan', 'teal', 'green', 'lime', 
                   'yellow', 'orange']
ModeType = Literal['light', 'dark']

# %% ../nbs/00_core.ipynb 6
def OpenProps(mode: ModeType = 'dark', color: ColorType = 'cyan'):
    """FastHTML header components for OpenProps UI
    
    Args:
        mode: 'light' or 'dark' 
        color: OpenProps OKLCH color
    """
    return [
        Link(rel='stylesheet', href='static/css/main.css'),
        
        theme_script
    ]
